"""
Technology detection rules.

To add a new technology: add a Rule to RULES. No other file needs to change.

Rule anatomy:
    name : display name returned to callers
    matchers : AND logic: all must pass; use AnyOf() inside for OR branches
    category : RuleCategory enum value
    confidence : 0.0 - 1.0; see scale below
    priority : higher = surfaced first in detailed results; see scale below

Confidence scale:
    1.0  unique config file or extension with no plausible false positives
    0.95 file/extension that is unambiguous in source code contexts
    0.9  standard file that is occasionally used by other tools
    0.8  combination of signals that is reliable but not exhaustive
    0.7  single weak signal with known edge cases
    0.6  directory-name heuristic; context-dependent

Priority scale:
    10   general language
    20   package manager / dependency file
    30   framework or specific library
    40   highly specific tooling with unique artefact
"""

from app.detector.matchers import (
    AllOf,
    AnyOf,
    HasDirectory,
    HasExtension,
    HasFilename,
    HasFileContent,
    HasFileGlob,
    HasPath,
)
from app.detector.models import Rule, RuleCategory

RULES: list[Rule] = [
    # Python
    Rule(
        name="Python",
        matchers=[HasExtension(".py")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,  # .py is used exclusively for Python source
        priority=10,
    ),
    Rule(
        # manage.py is generated by `django-admin startproject` and co-located
        # with a settings module. No other framework generates this file.
        name="Django",
        matchers=[HasFilename("manage.py")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        # poetry.lock is exclusively written by Poetry. pyproject.toml alone
        # is insufficient, it is shared with Hatch, setuptools, Flit, and uv.
        name="Poetry",
        matchers=[HasFilename("poetry.lock")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Pipfile is exclusively created by Pipenv.
        name="Pipenv",
        matchers=[HasFilename("Pipfile")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # uv.lock is exclusively written by Astral's uv package manager.
        name="uv",
        matchers=[HasFilename("uv.lock")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # setup.py / setup.cfg are the traditional setuptools entry points.
        # Either is sufficient. pyproject.toml alone is too broad.
        name="setuptools",
        matchers=[HasFilename("setup.py", "setup.cfg")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=0.9,  # setup.py could occasionally be a non-setuptools script
        priority=20,
    ),
    # JavaScript / TypeScript
    Rule(
        name="Node.js",
        matchers=[HasFilename("package.json")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # .ts and .tsx are unambiguous TypeScript extensions in source repos.
        # Note: .ts is also an MPEG transport stream extension, but this is
        # irrelevant in source code repositories.
        name="TypeScript",
        matchers=[HasExtension(".ts", ".tsx")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # next.config.* (js/ts/mjs/cjs) is generated by `create-next-app`
        # and is unique to Next.js.
        name="Next.js",
        matchers=[HasFileGlob("next.config.*")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # .vue single-file components are exclusive to Vue.js.
        name="Vue",
        matchers=[HasExtension(".vue")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # nuxt.config.* is generated by Nuxt only.
        name="Nuxt",
        matchers=[HasFileGlob("nuxt.config.*")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # angular.json is the Angular CLI workspace configuration file.
        name="Angular",
        matchers=[HasFilename("angular.json")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # vite.config.* is the Vite bundler configuration file.
        name="Vite",
        matchers=[HasFileGlob("vite.config.*")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # webpack.config.* is the Webpack bundler configuration file.
        name="Webpack",
        matchers=[HasFileGlob("webpack.config.*")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=30,
    ),
    # Mobile
    Rule(
        # pubspec.yaml is the Flutter/Dart project manifest. Requiring .dart
        # rules out pure Dart packages that also use pubspec.yaml but aren't
        # Flutter apps.
        name="Flutter",
        matchers=[HasFilename("pubspec.yaml"), HasExtension(".dart")],
        category=RuleCategory.MOBILE,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        # metro.config.* is the Metro bundler configuration, used exclusively
        # by React Native and Expo.
        name="React Native",
        matchers=[HasFileGlob("metro.config.*")],
        category=RuleCategory.MOBILE,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # AndroidManifest.xml is required in every Android project and has no
        # equivalent in any other mobile framework.
        name="Android",
        matchers=[HasFilename("AndroidManifest.xml")],
        category=RuleCategory.MOBILE,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # .swift source files are exclusive to Apple platform development.
        name="Swift",
        matchers=[HasExtension(".swift")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    Rule(
        # .kt / .kts are Kotlin source and script extensions.
        name="Kotlin",
        matchers=[HasExtension(".kt", ".kts")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    # Java / JVM
    Rule(
        name="Java Maven",
        matchers=[HasFilename("pom.xml")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Any of the four Gradle descriptor files is sufficient.
        name="Gradle",
        matchers=[
            HasFilename(
                "build.gradle",
                "build.gradle.kts",
                "settings.gradle",
                "settings.gradle.kts",
            )
        ],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # `application.properties` / `application.yml` at that path is the
        # Spring Boot convention and is a much stronger signal, but is still
        # not 100% unique (a non-Spring project could technically use that
        # filename). Requiring a JVM build file alongside it rules out
        # accidental matches.
        name="Spring Boot",
        matchers=[
            AnyOf(
                HasFilename("pom.xml"),
                HasFilename("build.gradle", "build.gradle.kts"),
            ),
            AnyOf(
                HasPath("src/main/resources/application.properties"),
                HasPath("src/main/resources/application.yml"),
                HasPath("src/main/resources/application.yaml"),
            ),
        ],
        category=RuleCategory.FRAMEWORK,
        confidence=0.85,
        priority=30,
    ),
    # .NET
    Rule(
        # .csproj (C#), .fsproj (F#), .vbproj (VB.NET) are MSBuild project
        # files exclusive to the .NET ecosystem.
        name=".NET",
        matchers=[HasExtension(".csproj", ".fsproj", ".vbproj")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    Rule(
        # .sln is the Visual Studio solution file, always present in .NET.
        name=".NET Solution",
        matchers=[HasExtension(".sln")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    # Rust
    Rule(
        name="Rust",
        matchers=[HasFilename("Cargo.toml")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    # Go
    Rule(
        name="Go",
        matchers=[HasFilename("go.mod")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    # PHP
    Rule(
        name="PHP",
        matchers=[HasExtension(".php")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # composer.json is the Composer package manifest for PHP.
        name="Composer",
        matchers=[HasFilename("composer.json")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # `artisan` is the Laravel CLI entry point, present at the root of
        # every Laravel project. No other framework uses this filename.
        name="Laravel",
        matchers=[HasFilename("artisan")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,  # artisan could theoretically be a non-Laravel script
        priority=30,
    ),
    # Ruby
    Rule(
        name="Ruby",
        matchers=[HasExtension(".rb")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # Gemfile is the Bundler dependency manifest for Ruby projects.
        name="Bundler",
        matchers=[HasFilename("Gemfile")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # config/routes.rb is generated by `rails new` and present in every
        # Rails application. No other Ruby framework uses this path.
        name="Ruby on Rails",
        matchers=[HasPath("config/routes.rb")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    # C / C++
    Rule(
        # REVISED: previous rule used HasExtension(".c", ".h"), which is OR
        # logic; a project with only .h files (common in C++ header-only
        # libraries) would falsely trigger C detection.
        # Fix: require .c specifically. .c is unambiguously C; .h alone is not.
        name="C",
        matchers=[HasExtension(".c")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # .cpp, .cc, .cxx are unambiguous C++ source extensions.
        # .hpp is the C++-specific header extension.
        name="C++",
        matchers=[HasExtension(".cpp", ".cc", ".cxx", ".hpp")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        name="CMake",
        matchers=[HasFilename("CMakeLists.txt")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # HasFileGlob with no wildcards is a case-insensitive exact match,
        # catching Makefile, makefile, MAKEFILE. The `makefile*` form also
        # catches Makefile.am (Automake) and Makefile.in.
        name="Make",
        matchers=[HasFileGlob("makefile*", "gnumakefile*")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=0.9,
        priority=20,
    ),
    # Embedded Systems
    Rule(
        # .ino is the Arduino sketch extension, used exclusively by the
        # Arduino IDE and compatible toolchains.
        name="Arduino",
        matchers=[HasExtension(".ino")],
        category=RuleCategory.EMBEDDED,
        confidence=1.0,
        priority=10,
    ),
    Rule(
        # platformio.ini is the PlatformIO project configuration file.
        name="PlatformIO",
        matchers=[HasFilename("platformio.ini")],
        category=RuleCategory.EMBEDDED,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # sdkconfig is generated by ESP-IDF's menuconfig tool.
        # idf_component.yml is the ESP-IDF component manager manifest.
        # Either is a reliable indicator; both are exclusive to ESP-IDF.
        name="ESP-IDF",
        matchers=[HasFilename("sdkconfig", "idf_component.yml")],
        category=RuleCategory.EMBEDDED,
        confidence=0.95,  # sdkconfig could be gitignored and absent
        priority=20,
    ),
    Rule(
        # .ioc is the STM32CubeMX peripheral configuration file, generated
        # exclusively by STM32CubeIDE / STM32CubeMX.
        name="STM32CubeIDE",
        matchers=[HasExtension(".ioc")],
        category=RuleCategory.EMBEDDED,
        confidence=1.0,
        priority=20,
    ),
    # Containers & Orchestration
    Rule(
        # HasFileGlob with a literal (no wildcards) performs a case-insensitive
        # exact match i.e., catches Dockerfile, dockerfile, DOCKERFILE, etc.
        name="Docker",
        matchers=[HasFileGlob("dockerfile")],
        category=RuleCategory.CONTAINER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Docker Compose",
        matchers=[
            HasFilename(
                "docker-compose.yml",
                "docker-compose.yaml",
                "compose.yml",
                "compose.yaml",
            )
        ],
        category=RuleCategory.CONTAINER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Chart.yaml is the Helm chart descriptor; every Helm chart requires it.
        name="Helm",
        matchers=[HasFilename("Chart.yaml", "Chart.yml")],
        category=RuleCategory.ORCHESTRATION,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # REVISED: HasDirectory("k8s", "kubernetes") is a directory-name
        # heuristic and can match unrelated projects.
        #
        # Strengthened: require the directory AND at least one .yaml/.yml file
        # inside it, which eliminates empty or misnamed directories.
        # Confidence is still moderate because the directory name is
        # conventional, not enforced.
        name="Kubernetes",
        matchers=[
            AnyOf(HasDirectory("k8s", "kubernetes")),
            AnyOf(
                HasPath("k8s/"),
                HasPath("kubernetes/"),
            ),
        ],
        category=RuleCategory.ORCHESTRATION,
        confidence=0.65,
        priority=20,
    ),
    # Infrastructure as Code
    Rule(
        # .tf is the Terraform (and OpenTofu) HCL configuration extension.
        name="Terraform",
        matchers=[HasExtension(".tf")],
        category=RuleCategory.DEVOPS,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # ansible.cfg is the Ansible configuration file. Its presence at any
        # level is a strong indicator of an Ansible-managed project.
        name="Ansible",
        matchers=[HasFilename("ansible.cfg")],
        category=RuleCategory.DEVOPS,
        confidence=0.9,
        priority=20,
    ),
    # CI/CD
    Rule(
        name="GitHub Actions",
        matchers=[HasPath(".github/workflows")],
        category=RuleCategory.CI_CD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # .gitlab-ci.yml is the GitLab CI/CD pipeline definition file.
        name="GitLab CI",
        matchers=[HasFilename(".gitlab-ci.yml")],
        category=RuleCategory.CI_CD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # .circleci/ is the CircleCI configuration directory.
        name="CircleCI",
        matchers=[HasDirectory(".circleci")],
        category=RuleCategory.CI_CD,
        confidence=0.95,
        priority=20,
    ),
    Rule(
        # .travis.yml is the Travis CI pipeline definition.
        name="Travis CI",
        matchers=[HasFilename(".travis.yml")],
        category=RuleCategory.CI_CD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Matches Jenkinsfile and Jenkinsfile.groovy (case-insensitive).
        name="Jenkins",
        matchers=[HasFileGlob("jenkinsfile*")],
        category=RuleCategory.CI_CD,
        confidence=0.95,
        priority=20,
    ),
    Rule(
        # azure-pipelines.yml is the Azure DevOps pipeline definition.
        name="Azure Pipelines",
        matchers=[HasFilename("azure-pipelines.yml")],
        category=RuleCategory.CI_CD,
        confidence=1.0,
        priority=20,
    ),
    # Web Technologies
    Rule(
        name="HTML",
        matchers=[HasExtension(".html", ".htm")],
        category=RuleCategory.FRONTEND,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        name="CSS",
        matchers=[HasExtension(".css")],
        category=RuleCategory.FRONTEND,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # .scss and .sass are the two Sass stylesheet syntax extensions.
        name="Sass",
        matchers=[HasExtension(".scss", ".sass")],
        category=RuleCategory.FRONTEND,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # tailwind.config.* is the Tailwind CSS configuration file.
        name="Tailwind CSS",
        matchers=[HasFileGlob("tailwind.config.*")],
        category=RuleCategory.FRONTEND,
        confidence=1.0,
        priority=30,
    ),
    # Data Science & Notebooks
    Rule(
        # .ipynb is the Jupyter Notebook format, used across Python data
        # science, research, and educational toolchains.
        name="Jupyter Notebook",
        matchers=[HasExtension(".ipynb")],
        category=RuleCategory.DATA_SCIENCE,
        confidence=1.0,
        priority=10,
    ),
    # Database Tooling
    Rule(
        # alembic.ini is the Alembic (SQLAlchemy migrations) configuration.
        name="Alembic",
        matchers=[HasFilename("alembic.ini")],
        category=RuleCategory.DATABASE,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # schema.prisma is the Prisma ORM schema definition file.
        name="Prisma",
        matchers=[HasFilename("schema.prisma")],
        category=RuleCategory.DATABASE,
        confidence=1.0,
        priority=30,
    ),
]
