"""
Technology detection rules.

To add a new technology: add a Rule to RULES. No other file needs to change.

Rule anatomy:
    name : display name returned to callers
    matchers : AND logic: all must pass; use AnyOf() inside for OR branches
    category : RuleCategory enum value
    confidence : 0.0 - 1.0; see scale below
    priority : higher = surfaced first in detailed results; see scale below

Confidence scale:
    1.0  unique config file or extension with no plausible false positives
    0.95 file/extension that is unambiguous in source code contexts
    0.9  standard file that is occasionally used by other tools
    0.8  combination of signals that is reliable but not exhaustive
    0.7  single weak signal with known edge cases
    0.6  directory-name heuristic; context-dependent

Priority scale:
    10   general language
    20   package manager / dependency file
    30   framework or specific library
    40   highly specific tooling with unique artefact
"""

from app.detector.matchers import (
    AllOf,
    AnyOf,
    HasDependency,
    HasDirectory,
    HasExtension,
    HasFilename,
    HasFileContent,
    HasFileGlob,
    HasJsonKey,
    HasPath,
    HasTomlSection,
)
from app.detector.models import Rule, RuleCategory

RULES: list[Rule] = [
    # Python
    Rule(
        name="Python",
        matchers=[HasExtension(".py")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,  # .py is used exclusively for Python source
        priority=10,
    ),
    Rule(
        # manage.py is generated by `django-admin startproject` and co-located
        # with a settings module. No other framework generates this file.
        name="Django",
        matchers=[HasFilename("manage.py")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        # poetry.lock is exclusively written by Poetry. pyproject.toml alone
        # is insufficient, it is shared with Hatch, setuptools, Flit, and uv.
        name="Poetry",
        matchers=[HasFilename("poetry.lock")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Pipfile is exclusively created by Pipenv.
        name="Pipenv",
        matchers=[HasFilename("Pipfile")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # uv.lock is exclusively written by Astral's uv package manager.
        name="uv",
        matchers=[HasFilename("uv.lock")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # setup.py / setup.cfg are the traditional setuptools entry points.
        # Either is sufficient. pyproject.toml alone is too broad.
        name="setuptools",
        matchers=[HasFilename("setup.py", "setup.cfg")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=0.9,  # setup.py could occasionally be a non-setuptools script
        priority=20,
    ),
    # JavaScript / TypeScript
    Rule(
        name="Node.js",
        matchers=[HasFilename("package.json")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # .ts and .tsx are unambiguous TypeScript extensions in source repos.
        # Note: .ts is also an MPEG transport stream extension, but this is
        # irrelevant in source code repositories.
        name="TypeScript",
        matchers=[HasExtension(".ts", ".tsx")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # next.config.* (js/ts/mjs/cjs) is generated by `create-next-app`
        # and is unique to Next.js.
        name="Next.js",
        matchers=[HasFileGlob("next.config.*")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # .vue single-file components are exclusive to Vue.js.
        name="Vue",
        matchers=[HasExtension(".vue")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # nuxt.config.* is generated by Nuxt only.
        name="Nuxt",
        matchers=[HasFileGlob("nuxt.config.*")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # angular.json is the Angular CLI workspace configuration file.
        name="Angular",
        matchers=[HasFilename("angular.json")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # vite.config.* is the Vite bundler configuration file.
        name="Vite",
        matchers=[HasFileGlob("vite.config.*")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # webpack.config.* is the Webpack bundler configuration file.
        name="Webpack",
        matchers=[HasFileGlob("webpack.config.*")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=30,
    ),
    # Mobile
    Rule(
        # pubspec.yaml is the Flutter/Dart project manifest. Requiring .dart
        # rules out pure Dart packages that also use pubspec.yaml but aren't
        # Flutter apps.
        name="Flutter",
        matchers=[HasFilename("pubspec.yaml"), HasExtension(".dart")],
        category=RuleCategory.MOBILE,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        # metro.config.* is the Metro bundler configuration, used exclusively
        # by React Native and Expo.
        name="React Native",
        matchers=[HasFileGlob("metro.config.*")],
        category=RuleCategory.MOBILE,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # AndroidManifest.xml is required in every Android project and has no
        # equivalent in any other mobile framework.
        name="Android",
        matchers=[HasFilename("AndroidManifest.xml")],
        category=RuleCategory.MOBILE,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # .swift source files are exclusive to Apple platform development.
        name="Swift",
        matchers=[HasExtension(".swift")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    Rule(
        # .kt / .kts are Kotlin source and script extensions.
        name="Kotlin",
        matchers=[HasExtension(".kt", ".kts")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    # Java / JVM
    Rule(
        name="Java Maven",
        matchers=[HasFilename("pom.xml")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Any of the four Gradle descriptor files is sufficient.
        name="Gradle",
        matchers=[
            HasFilename(
                "build.gradle",
                "build.gradle.kts",
                "settings.gradle",
                "settings.gradle.kts",
            )
        ],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # `application.properties` / `application.yml` at that path is the
        # Spring Boot convention and is a much stronger signal, but is still
        # not 100% unique (a non-Spring project could technically use that
        # filename). Requiring a JVM build file alongside it rules out
        # accidental matches.
        name="Spring Boot",
        matchers=[
            AnyOf(
                HasFilename("pom.xml"),
                HasFilename("build.gradle", "build.gradle.kts"),
            ),
            AnyOf(
                HasPath("src/main/resources/application.properties"),
                HasPath("src/main/resources/application.yml"),
                HasPath("src/main/resources/application.yaml"),
            ),
        ],
        category=RuleCategory.FRAMEWORK,
        confidence=0.85,
        priority=30,
    ),
    # .NET
    Rule(
        # .csproj (C#), .fsproj (F#), .vbproj (VB.NET) are MSBuild project
        # files exclusive to the .NET ecosystem.
        name=".NET",
        matchers=[HasExtension(".csproj", ".fsproj", ".vbproj")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    Rule(
        # .sln is the Visual Studio solution file, always present in .NET.
        name=".NET Solution",
        matchers=[HasExtension(".sln")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    # Rust
    Rule(
        name="Rust",
        matchers=[HasFilename("Cargo.toml")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    # Go
    Rule(
        name="Go",
        matchers=[HasFilename("go.mod")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    # PHP
    Rule(
        name="PHP",
        matchers=[HasExtension(".php")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # composer.json is the Composer package manifest for PHP.
        name="Composer",
        matchers=[HasFilename("composer.json")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # `artisan` is the Laravel CLI entry point, present at the root of
        # every Laravel project. No other framework uses this filename.
        name="Laravel",
        matchers=[HasFilename("artisan")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,  # artisan could theoretically be a non-Laravel script
        priority=30,
    ),
    # Ruby
    Rule(
        name="Ruby",
        matchers=[HasExtension(".rb")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # Gemfile is the Bundler dependency manifest for Ruby projects.
        name="Bundler",
        matchers=[HasFilename("Gemfile")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # config/routes.rb is generated by `rails new` and present in every
        # Rails application. No other Ruby framework uses this path.
        name="Ruby on Rails",
        matchers=[HasPath("config/routes.rb")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    # C / C++
    Rule(
        # REVISED: previous rule used HasExtension(".c", ".h"), which is OR
        # logic; a project with only .h files (common in C++ header-only
        # libraries) would falsely trigger C detection.
        # Fix: require .c specifically. .c is unambiguously C; .h alone is not.
        name="C",
        matchers=[HasExtension(".c")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # .cpp, .cc, .cxx are unambiguous C++ source extensions.
        # .hpp is the C++-specific header extension.
        name="C++",
        matchers=[HasExtension(".cpp", ".cc", ".cxx", ".hpp")],
        category=RuleCategory.LANGUAGE,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        name="CMake",
        matchers=[HasFilename("CMakeLists.txt")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # HasFileGlob with no wildcards is a case-insensitive exact match,
        # catching Makefile, makefile, MAKEFILE. The `makefile*` form also
        # catches Makefile.am (Automake) and Makefile.in.
        name="Make",
        matchers=[HasFileGlob("makefile*", "gnumakefile*")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=0.9,
        priority=20,
    ),
    # Embedded Systems
    Rule(
        # .ino is the Arduino sketch extension, used exclusively by the
        # Arduino IDE and compatible toolchains.
        name="Arduino",
        matchers=[HasExtension(".ino")],
        category=RuleCategory.EMBEDDED,
        confidence=1.0,
        priority=10,
    ),
    Rule(
        # platformio.ini is the PlatformIO project configuration file.
        name="PlatformIO",
        matchers=[HasFilename("platformio.ini")],
        category=RuleCategory.EMBEDDED,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # sdkconfig is generated by ESP-IDF's menuconfig tool.
        # idf_component.yml is the ESP-IDF component manager manifest.
        # Either is a reliable indicator; both are exclusive to ESP-IDF.
        name="ESP-IDF",
        matchers=[HasFilename("sdkconfig", "idf_component.yml")],
        category=RuleCategory.EMBEDDED,
        confidence=0.95,  # sdkconfig could be gitignored and absent
        priority=20,
    ),
    Rule(
        # FreeRTOSConfig.h is a mandatory, project-provided configuration
        # header required by every FreeRTOS port, it has no purpose
        # outside a FreeRTOS integration, making it a near-certain,
        # tree-only signal (no file content download required).
        #
        # The "FreeRTOS"/"freertos_kernel" directory names are a secondary,
        # slightly weaker signal that also catches projects which vendor
        # the FreeRTOS kernel source directly (e.g. STM32CubeMX-generated
        # projects under Middlewares/Third_Party/FreeRTOS, or the
        # upstream kernel's own "FreeRTOS-Kernel"/"freertos_kernel" layout)
        # without necessarily including a top-level FreeRTOSConfig.h at a
        # path this rule can see.
        #
        # NOTE: this rule intentionally does not attempt symbol-level
        # detection (e.g. xTaskCreate()/vTaskDelay() usage) because that
        # would require downloading arbitrary .c/.h source files, which
        # app.github.content_targets does not currently do for non-Arduino
        # embedded projects (see CONTENT_TARGET_COMPANION_EXTENSIONS, which
        # today is only populated alongside a .ino match). Adding that is a
        # deliberate follow-up (Phase 6's evidence_strength work is where
        # "declared vs. demonstrated" for this rule gets revisited), not an
        # oversight.
        name="FreeRTOS",
        matchers=[
            AnyOf(
                HasFilename("FreeRTOSConfig.h"),
                HasDirectory("FreeRTOS", "freertos_kernel", "FreeRTOS-Kernel"),
            )
        ],
        category=RuleCategory.EMBEDDED,
        confidence=0.9,
        priority=20,
    ),
    Rule(
        # .ioc is the STM32CubeMX peripheral configuration file, generated
        # exclusively by STM32CubeIDE / STM32CubeMX.
        name="STM32CubeIDE",
        matchers=[HasExtension(".ioc")],
        category=RuleCategory.EMBEDDED,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Extended Gerber (RS-274X) layer files are PCB manufacturing
        # output, produced by every major EDA tool (KiCad, EasyEDA, Eagle)
        # regardless of which one authored the design. A "gerber/" export
        # directory is also a near-universal convention. Either is
        # unambiguous evidence of a physical PCB design in the repo.
        name="PCB Design (Gerber)",
        matchers=[
            AnyOf(
                HasExtension(
                    ".gbr",
                    ".gtl",
                    ".gbl",
                    ".gts",
                    ".gbs",
                    ".gto",
                    ".gbo",
                    ".gko",
                    ".gml",
                    ".drl",
                ),
                HasDirectory("gerber"),
            )
        ],
        category=RuleCategory.EMBEDDED,
        confidence=0.9,
        priority=20,
    ),
    # Containers & Orchestration
    Rule(
        # HasFileGlob with a literal (no wildcards) performs a case-insensitive
        # exact match i.e., catches Dockerfile, dockerfile, DOCKERFILE, etc.
        name="Docker",
        matchers=[HasFileGlob("dockerfile")],
        category=RuleCategory.CONTAINER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Docker Compose",
        matchers=[
            HasFilename(
                "docker-compose.yml",
                "docker-compose.yaml",
                "compose.yml",
                "compose.yaml",
            )
        ],
        category=RuleCategory.CONTAINER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Chart.yaml is the Helm chart descriptor; every Helm chart requires it.
        name="Helm",
        matchers=[HasFilename("Chart.yaml", "Chart.yml")],
        category=RuleCategory.ORCHESTRATION,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # REVISED: HasDirectory("k8s", "kubernetes") is a directory-name
        # heuristic and can match unrelated projects.
        #
        # Strengthened: require the directory AND at least one .yaml/.yml file
        # inside it, which eliminates empty or misnamed directories.
        # Confidence is still moderate because the directory name is
        # conventional, not enforced.
        name="Kubernetes",
        matchers=[
            AnyOf(HasDirectory("k8s", "kubernetes")),
            AnyOf(
                HasPath("k8s/"),
                HasPath("kubernetes/"),
            ),
        ],
        category=RuleCategory.ORCHESTRATION,
        confidence=0.65,
        priority=20,
    ),
    # Infrastructure as Code
    Rule(
        # .tf is the Terraform (and OpenTofu) HCL configuration extension.
        name="Terraform",
        matchers=[HasExtension(".tf")],
        category=RuleCategory.DEVOPS,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # ansible.cfg is the Ansible configuration file. Its presence at any
        # level is a strong indicator of an Ansible-managed project.
        name="Ansible",
        matchers=[HasFilename("ansible.cfg")],
        category=RuleCategory.DEVOPS,
        confidence=0.9,
        priority=20,
    ),
    # CI/CD
    Rule(
        name="GitHub Actions",
        matchers=[HasPath(".github/workflows")],
        category=RuleCategory.CI_CD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # .gitlab-ci.yml is the GitLab CI/CD pipeline definition file.
        name="GitLab CI",
        matchers=[HasFilename(".gitlab-ci.yml")],
        category=RuleCategory.CI_CD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # .circleci/ is the CircleCI configuration directory.
        name="CircleCI",
        matchers=[HasDirectory(".circleci")],
        category=RuleCategory.CI_CD,
        confidence=0.95,
        priority=20,
    ),
    Rule(
        # .travis.yml is the Travis CI pipeline definition.
        name="Travis CI",
        matchers=[HasFilename(".travis.yml")],
        category=RuleCategory.CI_CD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Matches Jenkinsfile and Jenkinsfile.groovy (case-insensitive).
        name="Jenkins",
        matchers=[HasFileGlob("jenkinsfile*")],
        category=RuleCategory.CI_CD,
        confidence=0.95,
        priority=20,
    ),
    Rule(
        # azure-pipelines.yml is the Azure DevOps pipeline definition.
        name="Azure Pipelines",
        matchers=[HasFilename("azure-pipelines.yml")],
        category=RuleCategory.CI_CD,
        confidence=1.0,
        priority=20,
    ),
    # Web Technologies
    Rule(
        name="HTML",
        matchers=[HasExtension(".html", ".htm")],
        category=RuleCategory.FRONTEND,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        name="CSS",
        matchers=[HasExtension(".css")],
        category=RuleCategory.FRONTEND,
        confidence=0.95,
        priority=10,
    ),
    Rule(
        # .scss and .sass are the two Sass stylesheet syntax extensions.
        name="Sass",
        matchers=[HasExtension(".scss", ".sass")],
        category=RuleCategory.FRONTEND,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # tailwind.config.* is the Tailwind CSS configuration file.
        name="Tailwind CSS",
        matchers=[HasFileGlob("tailwind.config.*")],
        category=RuleCategory.FRONTEND,
        confidence=1.0,
        priority=30,
    ),
    # Data Science & Notebooks
    Rule(
        # .ipynb is the Jupyter Notebook format, used across Python data
        # science, research, and educational toolchains.
        name="Jupyter Notebook",
        matchers=[HasExtension(".ipynb")],
        category=RuleCategory.DATA_SCIENCE,
        confidence=1.0,
        priority=10,
    ),
    # Database Tooling
    Rule(
        # alembic.ini is the Alembic (SQLAlchemy migrations) configuration.
        name="Alembic",
        matchers=[HasFilename("alembic.ini")],
        category=RuleCategory.DATABASE,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # schema.prisma is the Prisma ORM schema definition file.
        name="Prisma",
        matchers=[HasFilename("schema.prisma")],
        category=RuleCategory.DATABASE,
        confidence=1.0,
        priority=30,
    ),
    # Content-based detection: these rely on downloaded manifest content
    # (see app.github.content_targets / analyzer include_content=True) and
    # simply never match when content wasn't downloaded, so they're safe to
    # keep enabled unconditionally.
    Rule(
        # FastAPI has no generated config file of its own; it's declared as
        # a regular dependency, so filename-based detection isn't possible.
        name="FastAPI",
        matchers=[HasDependency("fastapi")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        # Same story for React: no unique config file, only a package.json
        # dependency entry.
        name="React",
        matchers=[HasDependency("react")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,  # "react" as a dependency name is occasionally used loosely
        priority=30,
    ),
    # Python: frameworks, ORMs, task queues
    # A declared dependency is deterministic evidence the project uses that
    # package, the manifest is the authoritative source of truth for what
    # gets installed, so this category of rule has essentially no false
    # positive surface beyond a project vendoring/pinning something it
    # doesn't actually import (rare, and not something a static scan can
    # rule out for ANY tool).
    Rule(
        name="Flask",
        matchers=[HasDependency("flask")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        # "djangorestframework" is the exact PyPI/import distribution name;
        # no other package plausibly uses this exact name.
        name="Django REST Framework",
        matchers=[HasDependency("djangorestframework")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        name="Celery",
        matchers=[HasDependency("celery")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="Scrapy",
        matchers=[HasDependency("scrapy")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="Streamlit",
        matchers=[HasDependency("streamlit")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="SQLAlchemy",
        matchers=[HasDependency("sqlalchemy")],
        category=RuleCategory.DATABASE,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="pytest",
        matchers=[HasDependency("pytest")],
        category=RuleCategory.TESTING,
        confidence=0.95,
        priority=30,
    ),
    # Python: static analysis & documentation
    # [tool.X] section presence in pyproject.toml, or a tool-exclusive
    # config filename, means the project is actually configured to run
    # that tool, not merely capable of it.
    Rule(
        name="Ruff",
        matchers=[
            AnyOf(
                HasFilename("ruff.toml", ".ruff.toml"),
                HasTomlSection("pyproject.toml", "tool.ruff"),
            )
        ],
        category=RuleCategory.STATIC_ANALYSIS,
        confidence=0.95,
        priority=20,
    ),
    Rule(
        name="Black",
        matchers=[HasTomlSection("pyproject.toml", "tool.black")],
        category=RuleCategory.STATIC_ANALYSIS,
        confidence=0.9,  # Black is often run with zero config, so this only
        # catches projects that explicitly configured it; no false positives.
        priority=20,
    ),
    Rule(
        name="mypy",
        matchers=[
            AnyOf(
                HasFilename("mypy.ini", ".mypy.ini"),
                HasTomlSection("pyproject.toml", "tool.mypy"),
            )
        ],
        category=RuleCategory.STATIC_ANALYSIS,
        confidence=0.9,
        priority=20,
    ),
    Rule(
        name="isort",
        matchers=[
            AnyOf(
                HasFilename(".isort.cfg"),
                HasTomlSection("pyproject.toml", "tool.isort"),
            )
        ],
        category=RuleCategory.STATIC_ANALYSIS,
        confidence=0.85,
        priority=20,
    ),
    Rule(
        # .flake8 is an exclusive Flake8 config filename.
        name="Flake8",
        matchers=[HasFilename(".flake8")],
        category=RuleCategory.STATIC_ANALYSIS,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # .pylintrc is an exclusive Pylint config filename.
        name="Pylint",
        matchers=[HasFilename(".pylintrc")],
        category=RuleCategory.STATIC_ANALYSIS,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Sphinx",
        matchers=[HasDependency("sphinx")],
        category=RuleCategory.DOCUMENTATION,
        confidence=0.85,
        priority=20,
    ),
    # JavaScript / TypeScript: frameworks with unique config files
    # These frameworks each generate one project-scaffolding config file
    # that no other tool produces, mirroring the existing Next.js/Nuxt
    # pattern already in this file.
    Rule(
        # .svelte single-file components are exclusive to Svelte.
        name="Svelte",
        matchers=[HasExtension(".svelte")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        name="SvelteKit",
        matchers=[HasFileGlob("svelte.config.*")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        name="Remix",
        matchers=[HasFileGlob("remix.config.*")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        name="Gatsby",
        matchers=[HasFileGlob("gatsby-config.*")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # .astro components are exclusive to the Astro framework.
        name="Astro",
        matchers=[HasExtension(".astro")],
        category=RuleCategory.FRAMEWORK,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        # deno.json(c) is the Deno project configuration, exclusive to Deno.
        name="Deno",
        matchers=[HasFilename("deno.json", "deno.jsonc")],
        category=RuleCategory.LANGUAGE,
        confidence=1.0,
        priority=10,
    ),
    # JavaScript / TypeScript: backend frameworks & libraries (dependency)
    Rule(
        name="Express",
        matchers=[HasDependency("express")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        # "@nestjs/core" is an npm-scoped package name unique to NestJS.
        name="NestJS",
        matchers=[HasDependency("@nestjs/core")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        name="Redux",
        matchers=[HasDependency("redux")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.85,
        priority=30,
    ),
    Rule(
        name="GraphQL",
        matchers=[HasDependency("graphql")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.85,
        priority=20,
    ),
    # JavaScript / TypeScript: testing frameworks (dependency)
    Rule(
        name="Jest",
        matchers=[HasDependency("jest")],
        category=RuleCategory.TESTING,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        name="Mocha",
        matchers=[HasDependency("mocha")],
        category=RuleCategory.TESTING,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="Cypress",
        matchers=[HasDependency("cypress")],
        category=RuleCategory.TESTING,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        # Playwright's package can be either "playwright" or the scoped
        # "@playwright/test" test-runner package; either is definitive.
        name="Playwright",
        matchers=[
            AnyOf(HasDependency("playwright"), HasDependency("@playwright/test"))
        ],
        category=RuleCategory.TESTING,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="Vitest",
        matchers=[HasDependency("vitest")],
        category=RuleCategory.TESTING,
        confidence=0.95,
        priority=30,
    ),
    # JavaScript / TypeScript & general: monorepo tooling and static
    # analysis. Config filenames here are each exclusive to one tool.
    Rule(
        # "workspaces" is a top-level package.json key exclusive to npm/Yarn
        # monorepo workspace configuration.
        name="npm/Yarn Workspaces",
        matchers=[HasJsonKey("package.json", "workspaces")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=0.9,
        priority=20,
    ),
    Rule(
        name="Nx",
        matchers=[HasFilename("nx.json")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Turborepo",
        matchers=[HasFilename("turbo.json")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Lerna",
        matchers=[HasFilename("lerna.json")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Rush",
        matchers=[HasFilename("rush.json")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Matches .eslintrc, .eslintrc.js/.json/.yml (legacy) as well as
        # eslint.config.* (flat config, ESLint 9+). Both forms are
        # exclusive to ESLint.
        name="ESLint",
        matchers=[AnyOf(HasFileGlob(".eslintrc*"), HasFileGlob("eslint.config.*"))],
        category=RuleCategory.STATIC_ANALYSIS,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Prettier",
        matchers=[AnyOf(HasFileGlob(".prettierrc*"), HasFileGlob("prettier.config.*"))],
        category=RuleCategory.STATIC_ANALYSIS,
        confidence=0.95,
        priority=20,
    ),
    Rule(
        name="Stylelint",
        matchers=[HasFileGlob(".stylelintrc*")],
        category=RuleCategory.STATIC_ANALYSIS,
        confidence=0.95,
        priority=20,
    ),
    # Package manager lockfiles (JS ecosystem)
    # A lockfile is written by exactly one tool; its mere presence is
    # unambiguous, unlike package.json which all of these tools share.
    Rule(
        name="Yarn",
        matchers=[HasFilename("yarn.lock")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="npm",
        matchers=[HasFilename("package-lock.json")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="pnpm",
        matchers=[HasFilename("pnpm-lock.yaml")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Bun",
        matchers=[HasFilename("bun.lockb", "bun.lock")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    # Java / JVM: frameworks and testing
    # Neither Maven's pom.xml nor Gradle's build.gradle(.kts) is parseable
    # by the generic DEPENDENCY_PARSERS registry (they're XML/Groovy/Kotlin
    # DSL, not JSON/TOML), so these use HasFileContent to look for the
    # distinctive artifact/dependency identifier string instead. Both are
    # fixed, well-known filenames, so this is still a targeted, not a
    # blanket, substring search.
    Rule(
        name="JUnit",
        matchers=[
            AnyOf(
                HasFileContent("pom.xml", "junit"),
                HasFileContent("build.gradle", "junit"),
                HasFileContent("build.gradle.kts", "junit"),
            )
        ],
        category=RuleCategory.TESTING,
        confidence=0.85,
        priority=30,
    ),
    Rule(
        # "quarkus" as a Maven/Gradle artifact/group prefix is exclusive to
        # the Quarkus framework.
        name="Quarkus",
        matchers=[
            AnyOf(
                HasFileContent("pom.xml", "quarkus"),
                HasFileContent("build.gradle", "quarkus"),
                HasFileContent("build.gradle.kts", "quarkus"),
            )
        ],
        category=RuleCategory.FRAMEWORK,
        confidence=0.85,
        priority=30,
    ),
    Rule(
        name="Micronaut",
        matchers=[
            AnyOf(
                HasFileContent("pom.xml", "micronaut"),
                HasFileContent("build.gradle", "micronaut"),
                HasFileContent("build.gradle.kts", "micronaut"),
            )
        ],
        category=RuleCategory.FRAMEWORK,
        confidence=0.85,
        priority=30,
    ),
    Rule(
        # checkstyle.xml is Checkstyle's exclusive rule-configuration file.
        name="Checkstyle",
        matchers=[HasFilename("checkstyle.xml")],
        category=RuleCategory.STATIC_ANALYSIS,
        confidence=0.9,
        priority=20,
    ),
    # C / C++: package managers and alternative build systems
    Rule(
        name="Conan",
        matchers=[HasFilename("conanfile.txt", "conanfile.py")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="vcpkg",
        matchers=[HasFilename("vcpkg.json")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Bazel",
        matchers=[HasFilename("WORKSPACE", "WORKSPACE.bazel", "BUILD.bazel")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # build.ninja is a Ninja-generated build file; hand-written Ninja
        # projects use the same filename, so either way it's Ninja.
        name="Ninja",
        matchers=[HasFilename("build.ninja")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Meson",
        matchers=[HasFilename("meson.build")],
        category=RuleCategory.BUILD_SYSTEM,
        confidence=1.0,
        priority=20,
    ),
    # Embedded / IoT
    Rule(
        # west.yml is the manifest for Zephyr RTOS's West meta-tool,
        # exclusive to Zephyr-based projects.
        name="Zephyr RTOS",
        matchers=[HasFilename("west.yml")],
        category=RuleCategory.EMBEDDED,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # mbed_app.json is the Mbed OS application configuration file.
        name="Mbed OS",
        matchers=[HasFilename("mbed_app.json")],
        category=RuleCategory.EMBEDDED,
        confidence=1.0,
        priority=20,
    ),
    # DevOps: provisioning & configuration management
    Rule(
        name="Vagrant",
        matchers=[HasFilename("Vagrantfile")],
        category=RuleCategory.DEVOPS,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # *.pkr.hcl is HashiCorp Packer's exclusive template extension.
        # HasFileGlob (not HasExtension) is required here: HasExtension only
        # inspects the text after the final dot, which would see ".hcl" and
        # miss the "pkr" that makes this Packer-specific.
        name="Packer",
        matchers=[HasFileGlob("*.pkr.hcl")],
        category=RuleCategory.DEVOPS,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Puppetfile is Puppet's exclusive module-dependency manifest.
        # (Note: the .pp source extension is intentionally not used here,
        # as it collides with Pascal source files.)
        name="Puppet",
        matchers=[HasFilename("Puppetfile")],
        category=RuleCategory.DEVOPS,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # metadata.rb is Chef's cookbook descriptor, required in every Chef
        # cookbook and not used by any other tool.
        name="Chef",
        matchers=[HasFilename("metadata.rb")],
        category=RuleCategory.DEVOPS,
        confidence=0.85,
        priority=20,
    ),
    # Cloud: IaC and serverless frameworks with unique project files
    Rule(
        name="Pulumi",
        matchers=[HasFilename("Pulumi.yaml", "Pulumi.yml")],
        category=RuleCategory.CLOUD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # cdk.json is generated by `cdk init` and required for every AWS CDK
        # app; no other tool uses this filename.
        name="AWS CDK",
        matchers=[HasFilename("cdk.json")],
        category=RuleCategory.CLOUD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Serverless Framework",
        matchers=[HasFilename("serverless.yml", "serverless.yaml")],
        category=RuleCategory.CLOUD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # samconfig.toml is written exclusively by `sam deploy --guided` /
        # `sam init` for AWS Serverless Application Model projects.
        name="AWS SAM",
        matchers=[HasFilename("samconfig.toml")],
        category=RuleCategory.CLOUD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Google Cloud Build",
        matchers=[HasFilename("cloudbuild.yaml", "cloudbuild.yml")],
        category=RuleCategory.CLOUD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # .bicep is Azure Bicep's exclusive source extension.
        name="Azure Bicep",
        matchers=[HasExtension(".bicep")],
        category=RuleCategory.CLOUD,
        confidence=1.0,
        priority=20,
    ),
    # Databases & ORMs
    Rule(
        name="Flyway",
        matchers=[HasFilename("flyway.conf", "flyway.toml")],
        category=RuleCategory.DATABASE,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        name="Liquibase",
        matchers=[HasFilename("liquibase.properties")],
        category=RuleCategory.DATABASE,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        name="TypeORM",
        matchers=[HasDependency("typeorm")],
        category=RuleCategory.DATABASE,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="Sequelize",
        matchers=[HasDependency("sequelize")],
        category=RuleCategory.DATABASE,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="Mongoose",
        matchers=[HasDependency("mongoose")],
        category=RuleCategory.DATABASE,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="Prisma ORM",
        matchers=[HasDependency("@prisma/client")],
        category=RuleCategory.DATABASE,
        confidence=0.9,
        priority=30,
    ),
    # ML / AI
    # A declared dependency on one of these packages is the standard,
    # deterministic way a static scan can identify ML/AI framework usage.
    Rule(
        name="TensorFlow",
        matchers=[HasDependency("tensorflow")],
        category=RuleCategory.ML_AI,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        # PyPI/import name for PyTorch is "torch".
        name="PyTorch",
        matchers=[HasDependency("torch")],
        category=RuleCategory.ML_AI,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        name="scikit-learn",
        matchers=[HasDependency("scikit-learn")],
        category=RuleCategory.ML_AI,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        name="Keras",
        matchers=[HasDependency("keras")],
        category=RuleCategory.ML_AI,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="XGBoost",
        matchers=[HasDependency("xgboost")],
        category=RuleCategory.ML_AI,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        name="LangChain",
        matchers=[HasDependency("langchain")],
        category=RuleCategory.ML_AI,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        # "transformers" is the exact Hugging Face package name; slightly
        # lower confidence than other ML entries since it's a more generic
        # English word than e.g. "tensorflow" or "xgboost".
        name="Hugging Face Transformers",
        matchers=[HasDependency("transformers")],
        category=RuleCategory.ML_AI,
        confidence=0.8,
        priority=30,
    ),
    Rule(
        name="OpenAI SDK",
        matchers=[HasDependency("openai")],
        category=RuleCategory.ML_AI,
        confidence=0.85,
        priority=30,
    ),
    # Data Science
    Rule(
        name="pandas",
        matchers=[HasDependency("pandas")],
        category=RuleCategory.DATA_SCIENCE,
        confidence=0.95,
        priority=20,
    ),
    Rule(
        name="NumPy",
        matchers=[HasDependency("numpy")],
        category=RuleCategory.DATA_SCIENCE,
        confidence=0.95,
        priority=20,
    ),
    Rule(
        name="Matplotlib",
        matchers=[HasDependency("matplotlib")],
        category=RuleCategory.DATA_SCIENCE,
        confidence=0.9,
        priority=20,
    ),
    Rule(
        # .R is the R language source extension.
        name="R",
        matchers=[HasExtension(".r")],
        category=RuleCategory.LANGUAGE,
        confidence=0.9,
        priority=10,
    ),
    Rule(
        # .Rmd is the R Markdown extension, exclusive to R's literate
        # programming/reporting toolchain.
        name="R Markdown",
        matchers=[HasExtension(".rmd")],
        category=RuleCategory.DATA_SCIENCE,
        confidence=0.95,
        priority=20,
    ),
    # Documentation tools
    Rule(
        name="MkDocs",
        matchers=[HasFilename("mkdocs.yml", "mkdocs.yaml")],
        category=RuleCategory.DOCUMENTATION,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Docusaurus",
        matchers=[HasFileGlob("docusaurus.config.*")],
        category=RuleCategory.DOCUMENTATION,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Read the Docs",
        matchers=[HasFilename(".readthedocs.yaml", ".readthedocs.yml")],
        category=RuleCategory.DOCUMENTATION,
        confidence=1.0,
        priority=20,
    ),
    # Cloud / Containers: additional orchestration tooling
    Rule(
        name="Skaffold",
        matchers=[HasFilename("skaffold.yaml", "skaffold.yml")],
        category=RuleCategory.ORCHESTRATION,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Kustomize",
        matchers=[HasFilename("kustomization.yaml", "kustomization.yml")],
        category=RuleCategory.ORCHESTRATION,
        confidence=1.0,
        priority=20,
    ),
    # CI/CD: additional providers
    Rule(
        name="Buildkite",
        matchers=[HasDirectory(".buildkite")],
        category=RuleCategory.CI_CD,
        confidence=0.9,
        priority=20,
    ),
    Rule(
        name="Drone CI",
        matchers=[HasFilename(".drone.yml")],
        category=RuleCategory.CI_CD,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Bitbucket Pipelines",
        matchers=[HasFilename("bitbucket-pipelines.yml")],
        category=RuleCategory.CI_CD,
        confidence=1.0,
        priority=20,
    ),
    # Mobile: additional platforms & package managers
    Rule(
        # project.pbxproj is Xcode's project descriptor, generated for every
        # iOS/macOS Xcode project regardless of the enclosing .xcodeproj
        # bundle's name; matched here by filename, not directory, since
        # the bundle name varies per app.
        name="Xcode Project",
        matchers=[HasFileGlob("*.pbxproj")],
        category=RuleCategory.MOBILE,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Podfile is CocoaPods' exclusive dependency manifest for iOS/macOS.
        name="CocoaPods",
        matchers=[HasFilename("Podfile")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        # Package.swift is Swift Package Manager's exclusive manifest.
        name="Swift Package Manager",
        matchers=[HasFilename("Package.swift")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    Rule(
        name="Ionic",
        matchers=[HasFilename("ionic.config.json")],
        category=RuleCategory.MOBILE,
        confidence=1.0,
        priority=30,
    ),
    Rule(
        name="NuGet",
        matchers=[HasFilename("nuget.config", "packages.config")],
        category=RuleCategory.PACKAGE_MANAGER,
        confidence=1.0,
        priority=20,
    ),
    # PHP: frameworks (dependency)
    Rule(
        # "symfony/framework-bundle" is the exact Composer package name for
        # the core Symfony framework bundle.
        name="Symfony",
        matchers=[HasDependency("symfony/framework-bundle")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        name="Drupal",
        matchers=[HasDependency("drupal/core")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        # WordPress ships wp-config.php (or the wp-config-sample.php
        # template it's copied from) at the project root; both names are
        # exclusive to WordPress installs.
        name="WordPress",
        matchers=[HasFilename("wp-config.php", "wp-config-sample.php")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.95,
        priority=30,
    ),
    Rule(
        name="PHPUnit",
        matchers=[HasDependency("phpunit/phpunit")],
        category=RuleCategory.TESTING,
        confidence=0.9,
        priority=30,
    ),
    # Ruby: frameworks & testing (dependency)
    Rule(
        name="Sinatra",
        matchers=[HasDependency("sinatra")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="RSpec",
        matchers=[HasDependency("rspec")],
        category=RuleCategory.TESTING,
        confidence=0.9,
        priority=30,
    ),
    # Go: frameworks & ORMs (dependency; short module names via go.mod)
    Rule(
        name="Gin",
        matchers=[HasDependency("gin")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="Echo",
        matchers=[HasDependency("echo")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.85,  # "echo" is a common word; still a specific module short-name match
        priority=30,
    ),
    Rule(
        name="Fiber",
        matchers=[HasDependency("fiber")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="GORM",
        matchers=[HasDependency("gorm")],
        category=RuleCategory.DATABASE,
        confidence=0.9,
        priority=30,
    ),
    # Rust: frameworks & libraries (dependency via Cargo.toml)
    Rule(
        name="Actix Web",
        matchers=[HasDependency("actix-web")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,
        priority=30,
    ),
    Rule(
        name="Rocket",
        matchers=[HasDependency("rocket")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.85,
        priority=30,
    ),
    Rule(
        name="Tokio",
        matchers=[HasDependency("tokio")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,
        priority=20,
    ),
    Rule(
        name="Serde",
        matchers=[HasDependency("serde")],
        category=RuleCategory.FRAMEWORK,
        confidence=0.9,
        priority=20,
    ),
    Rule(
        name="Diesel",
        matchers=[HasDependency("diesel")],
        category=RuleCategory.DATABASE,
        confidence=0.9,
        priority=30,
    ),
]
